name       : python-cheetah
version    : 3.2.5
release    : 3
source     :
    - https://files.pythonhosted.org/packages/50/d5/34b30f650e889d0d48e6ea9337f7dcd6045c828b9abaac71da26b6bdc543/Cheetah3-3.2.5.tar.gz : ececc9ca7c58b9a86ce71eb95594c4619949e2a058d2a1af74c7ae8222515eb1
license    : MIT
component  : programming.python
summary    : Template engine and code generation tool
description: |
    Cheetah is an open source template engine and code generation tool. It can be used standalone or combined with other tools and frameworks. Web development is its principle use, but Cheetah is very flexible and is also being used to generate C++ game code, Java, sql, form emails and even Python code.
builddeps  :
    - python3-devel
setup      : |
    %python3_setup
install    : |
    %python3_install
