name       : python-cheetah
version    : 2.4.4
release    : 1
source     :
    - https://pypi.python.org/packages/cd/b0/c2d700252fc251e91c08639ff41a8a5203b627f4e0a2ae18a6b662ab32ea/Cheetah-2.4.4.tar.gz : be308229f0c1e5e5af4f27d7ee06d90bb19e6af3059794e5fd536a6f29a9b550
license    : MIT
component  : programming.python
summary    : template engine and code generation tool
description: |
    Cheetah is an open source template engine and code generation tool.  It can be used standalone or combined with other tools and frameworks. Web development is its principle use, but Cheetah is very flexible and is also being used to generate C++ game code, Java, sql, form emails and even Python code.
setup      : |
    %python_setup
install    : |
    %python_install
