name       : python-cheetah
version    : 3.3.2
release    : 8
source     :
    - https://github.com/CheetahTemplate3/cheetah3/archive/refs/tags/3.3.2.tar.gz : 6ec9cbbf9054b826d289d5e289cb0e801f6bb5a35b81155dd288e57003617120
homepage   : https://cheetahtemplate.org/
license    : MIT
component  : programming.python
summary    : Template engine and code generation tool
description: |
    Cheetah is an open source template engine and code generation tool. It can be used standalone or combined with other tools and frameworks. Web development is its principle use, but Cheetah is very flexible and is also being used to generate C++ game code, Java, sql, form emails and even Python code.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python3
setup      : |
    %python3_setup
install    : |
    %python3_install
